### ISSUE TITLE
BTT mini 12864 V2.0 screen to Creality 4.2.2 board.

### ISSUE THREAD

**Issue by Dwall36b** [bigtreetech/BGTHREETECH-MINI-12864-V1.0#19]
I am trying to connect the mini12864 screen to the 4.2.2 board from Creality. I am still very new to all of this. Upon opening and trying to plug and play, well to much my surprise... it didn't work. The screen lit up, but didn't display anything. Upon searching the web, I found that I need to flash the firmware after compiling.

I do not have the knowledge compacity to do such things yet, I am still trying to learn. But, I am working on learning how to compile firmware of my own. 

However, here comes my question and reason behind this post... I have know how to download firmware, and place the bin file on my sd card. Is there any pre-compiled firmware for the screen and/ or the 422 board? Or is this something I am going to have to just buckle down and learn how to do firmware?

Any and all help is appreciated! Learning very quickly that the 3D printing community is very knowledgeable and respecting! Thanks all and have a blessed day!

**Comment by Otann** [comment]
There is this reddit thread that might help you.
I did the suggested wiring, but I can't get the rotational knob to work though

https://www.reddit.com/r/klippers/comments/sw9mej/12864_mini_display_working_with_stock_creality/
